examples/apps/plainqt/mainwindow.cpp

it seems like the command line arguments this example app has been removed from the server.

stop passing non-existing arguments to the maliit server from example app

---

input-context/minputcontext.cpp

On rare case wrong preedit was committed, e.g:
- while preedit existed, the application programmatically changed editor
content -> reset()
- focus removed from editor -> commit()

Clear preedit state on input context reset

---

input-context/main.cpp

The fixes compatibility with Qt 5.5 where this string has changed, as detailed in issue #13

Replace hard coded string with QPlatformInputContextFactoryInterface_iid

---

maliit-glib/maliitattributeextensionregistry.c
maliit-glib/maliitbus.c
maliit-glib/maliitinputmethod.c
maliit-glib/maliitsettingsmanager.c

We should make these transfer-none (i.e. make the caller ref them explicitly). It's more conventional with the names we've given them (get vs new).

Don't require unref from GDBusProxy helpers

---

src/mimsettingsqsettings.cpp
tests/ut_mimonscreenplugins/ut_mimonscreenplugins.cpp
tests/ut_mimpluginmanagerconfig/ut_mimpluginmanagerconfig.cpp

Some of the tests weren't working because either the QSettings changes weren't being flushed to disk, or the tests were actually reading settings from the builder's existing configuration.

Fix broken tests

---

input-context/minputcontext.cpp

Just like in maliit-glib, we should check if the MALIIT_SERVER_ADDRESS has been set. This way we use that dbus address.
A use case here, is when we create a proxy socket for the clients to read/write from while the maliit server still uses the original abstract socket. This way we can create a real socket for it to be bind mounted over an lxc container and the applications in the lxc container can still use the host maliit server.
Doing this works find for gtk since maliit-glib checks this env. As for qt it does not, and assumes the abstract location.

Need to allow the qt input context dbus server address to be overridden

---

src/qt/plugins/shellintegration/qwaylandinputpanelsurface.cpp

Otherwise we would never request the view display.

Make sure the surface gets initialized

---

passthroughserver/main.cpp
src/maliit/standaloneinputmethod.cpp

This adds the envar MALIIT_FORCE_DBUS_CONNECTION to allow maliit to
force use of a dbus type connections instead of wayland one.

Add envar to force a dbus input context connection

---

CMakeLists.txt

It currently installs to [QT_PLUGIN_PATH]/platforminputcontext, this is incorrect, the correct path for qt is [QT_PLUGIN_PATH]/platforminputcontexts

Install input context in the right directory

---

src/windowgroup.cpp

This patch ensures that maliit continues to update the input method area
after the keyboard has been dismissed. This allows keyboard hiding
animations to provide a smooth transition between the showing and hiding
states.

Update input method area when hiding the keyboard

---

CMakeLists.txt

This is particularly useful to avoid the dependency on QtWidgets which
is only used for the examples

Add cmake option to build examples

---

cmake/FindQtWaylandScanner.cmake

Do not search only in /usr/lib64 as this location won't be present on 32-bit systems.

Fix search for qtwaylandscanner on 32-bit architectures

---

connection/waylandinputmethodconnection.cpp

This allows the compositor to show the panel again as the context
massively changes.

Show the panel as the keyboard interface is reset

---

input-context/minputcontext.cpp

The existing mapping between Qt::ScreenOrientation values and rotation angles is wrong.
This patch fixes it by simply using the existing function for this from Qt.
E.g.:
If primary angle is Landscape and the given orientation is Portrait, the resulting rotation angle is 90, not 270 as in that switch. Documentation for Qt::PortraitOrientation says it is " rotated 90 degree clockwise relative to landscape."

Fix mapping between screen orientations and rotation angles.

---

cmake/FindGIO.cmake

So that it may be possible to build with cmake 3.5 if needed for
Ubuntu Touch, clean up the FindGIO.cmake a bit to work properly
with the current build layout of framework when using older cmake.

Clean up FindGIO.cmake to allow working with older cmake

---

input-context/minputcontext.cpp
input-context/minputcontext.h

When using maliit-server and the dbus protocol for input method handling, as is done on Ubuntu Touch, there are a few problematic areas, which are solved by patches included in the Ubuntu/UBports packages of maliit framework. This pulls in a couple more that have not yet been merged upstream (and aren't in other PRs).

Pull in some of the Ubuntu Touch patches

---

connection/waylandinputmethodconnection.cpp

It's somewhat what's expected. The alternative is getting a full keyboard after all.

input_method_v1: Treat content_purpose_digits just like content_purpose_number

---

CMakeLists.txt

c76426d262 renamed the README to README.md, but this change was never
reflected in CMakeLists.txt, thus the install target would fail.
Unrelated, but why are the README and NEWS file being installed at all? And even the LICENSE file tbh, they don't seem to belong in a doc directory on the system.

Fix installing README

---

connection/waylandinputmethodconnection.cpp

If we the keyboard is hidden (using the close gesture or a similar
method) and the surrounding text changes (suggesting the user tapped the
same text field but in a different place), re-show the keyboard.
This assumes the user hid the keyboard manually, then tapped the
textfield again to request it be reshown.

Re-show the keyboard on wayland surrounding text changes

---

src/maliit-defines.prf.in

Before the cmake switch these were all full paths.

Fix maliit-defines.prf paths

---

input-context/minputcontext.cpp

Otherwise a hardware keyboard plugin would be fighting with the compose
plugin.
Also removed an unnecessary null check.

Use compose input plugin fallback only if key direction is disabled

---

CMakeLists.txt
connection/dbusinputcontextconnection.cpp
input-context/minputcontext.cpp
input-context/minputcontext.h
passthroughserver/main.cpp
src/logging.cpp
src/logging.h
src/mattributeextensionmanager.cpp
src/mimpluginmanager.cpp
src/mimserver.cpp
src/mimsettings.cpp
src/quick/inputmethodquick.cpp
src/quick/keyoverridequick.cpp
src/windowgroup.cpp
src/xcbplatform.cpp
tests/dummyimplugin/dummyinputmethod.cpp
tests/dummyimplugin3/dummyinputmethod3.cpp

More standard logging, allows better control on what gets printed and avoids collision with QT_MESSAGE_PATTERN, etc. Also console.log() etc will not be filtered out by default which to me has appeared to confuse some people trying to hack the keyboard before finding out the environment variable.

Use QLoggingCategories for logging

---

input-context/minputcontext.cpp
src/maliit/plugins/abstractinputmethod.h

Got changed in commit b9f448fcc
Slightly hard to follow, but the Qt::LandscapeOrientation & friends
are defined with clockwise orientation. The QScreen::angleBetween()
doesn't explicitly define the direction but the results match how much
the physical screen would need to be rotated clockwise, and commonly
clockwise angles are used within Qt.
But now, if the display is rotated 90 degrees clockwise, the application
UI should be rotated to opposite direction to remain shown correctly,
i.e. to 270.
Thus switch the parameter order to angleBetween() and define the resulting
appOrientation angle to hopefully avoid confusion in the future.
---
Took a peek at the maliit-keyboard side too and looks like src/plugin/inputmethod.cpp / rotationAngleToScreenOrientation() is indeed assuming either …

Fix application orientation angle back to clockwise

---

src/windowgroup.cpp

As Mir has a special window type for input method panel, set the magic
number in the window type flags when setting up the window, to enable
plugins working correctly where Mir is used.

WindowGroup: Add the Mir input panel window type flag

---

tests/ut_mimserveroptions/ut_mimserveroptions.cpp

With gcc-12 having the operator== in anonymous namespace for a struct which
is in the global namespace results in a lengthy compilation error. Moving
this non-mmember function into the global namespace fixes the issue.
Fixes #112

ut_mimserveroptions: Move the operator== definition to global namespace

---

tests/ft_mimpluginmanager/ft_mimpluginmanager.cpp

If we don't save QList to a variable, it becomes deleted, and pointer returned by findPluginDescriptions becomes invalid. Then trying to call description->enabled() results in a segmentation fault.
Here is valgrind report:
```
==17249== Invalid read of size 8
==17249==    at 0x49D0EB0: MImPluginDescription::enabled() const (plugindescription.cpp:72)
==17249==    by 0x12BB69: Ft_MIMPluginManager::testPluginDescriptions() (ft_mimpluginmanager.cpp:213)
==17249==    by 0x53D17BD: QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (qmetaobject.cpp:2303)
==17249==    by 0x489FBD0: invoke …
```

Prevent QList returned by subject->pluginDescriptions from being deleted

---

src/mimhwkeyboardtracker.cpp

Fix #56 
The issue was due to a mishandling of ioctl requests: from what I could gather (the documentation is scarse), the length argument in `EVIOCGBIT(reg,len)` should be expressed in bytes and not in bits.
@nrndda would you mind confirming that this patch fixes #56 for you as well?

Fix stack smashing due to mishandled ioctl bits reading

---

connection/serverdbusaddress.cpp

As dbus has now changed to make tmpdir behave the same as dir, socket creation fails when the directory does not exist, and it is no longer automatically removed upon exit. Instead, switch to a well known name under XDG_RUNTIME_DIR, as only one instance of the dbus service can exist at a time, per user.

connection: Move dbus socket to well known path in XDG_RUNTIME_DIR
